server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: method_route
#        uri: http://httpbin.org:80/get
        uri: lb://EUREKACLIENT
#        filters:
#        - AddRequestHeader=X-Request-Foo, Bar
#        predicates:
#        - Method=GET
        filters:
        - RewritePath=/foo/(?<segment>.*), /$\{segment}
        predicates:
        - Path=/foo/**